### PR TITLE
Resolve props template usage composition api

### PR DESCRIPTION
**Pull request by xi-osman**
## Description of Problem
Was not able to run the provided composition template code snippet and realized its because the props object was not returned.
## Proposed Solution
Added the props property and also returned props so the template can reference it.

### CODE REVIEW

**Comment by NataliaTepluhina** [comment]
@xi-osman thank you for the contribution! However, the snippet works without returning `props` explicitly: https://codesandbox.io/s/setup-with-props-phsye?file=/src/Book.vue

**Comment by xi-osman** [comment]
@NataliaTepluhina Awesome that worked! Would we want to remove the 'props.' from the template and just leave 'collectionName' then?  

```
<!-- MyBook.vue -->
<template>
  <div>{{ props.collectionName }}: {{ readersNumber }} {{ book.title }}</div>
</template>
```

**Comment by NataliaTepluhina** [comment]
@xi-osman yes, that is a mistake I guess 😅  Would you mind doing this change on your pull request?

**Comment by xi-osman** [comment]
@NataliaTepluhina Sure! already submitted a new commit 😎

**Review by NataliaTepluhina — APPROVED** [review]
Thank you for fixing it!

**Pull request merged**
