### PR TITLE
chore: remove beta banner from docs

### PR DESCRIPTION
**Pull request by bencodezen**

### CODE REVIEW

**Review by phanan — COMMENTED** [review]
Should we remove the banner component as well?

**Comment by Alex-Sokolov** [comment]
And what about https://v3.vuejs.org/guide/contributing/translations.html#can-we-start-translating-vue-3-docs if this merged

**Comment by bencodezen** [comment]
> And what about [v3.vuejs.org/guide/contributing/translations.html#can-we-start-translating-vue-3-docs](https://v3.vuejs.org/guide/contributing/translations.html#can-we-start-translating-vue-3-docs) if this merged

Great catch @Alex-Sokolov! Gonna issue a PR to fix this now!

**Comment by bencodezen** [comment]
@phanan I was thinking it might be nice to keep the Banner component for other things in the future if we have other call to actions. So maybe I'll just refactor it so it is more generic.

**Comment by bencodezen** [comment]
@phanan Updated it with the new changes and feedback!

**Review by phanan — APPROVED** [review]
Nice, thanks for the proactive work on this Ben!

**Pull request merged**
