### PR TITLE
docs(webpack): add installation instructions

### PR DESCRIPTION
**Pull request by evenstensberg**
## Description of Problem

There's no way of knowing how to bundle vue 3 with webpack 5.

## Proposed Solution

Documentation on this

### CODE REVIEW

**Comment by NataliaTepluhina** [comment]
@evenstensberg thank you for the contribution! However, in this section, we only cover _Vue-specific_ tools from our own ecosystem. That's why we don't cover webpack or Parcel builds here, for example.

However, I believe we could add a link to the end of the Vue CLI section (CLI uses webpack under the hood), mentioning that if you prefer to set up the webpack build manually, you can use [vue-loader](https://vue-loader.vuejs.org/guide/#manual-setup)

**Comment by evenstensberg** [comment]
Could you add that?

**Comment by NataliaTepluhina** [comment]
@evenstensberg Sure! But I would need to open a different PR because I can't make changed to your forked repository

**Comment by skirtles-code** [comment]
I've been experimenting with ways of wording this and I think it might make more sense to add a note to the `npm` section rather than the `CLI` section. I'm going to ruminate on it a little more but I should have a PR up in the next few days.

**Pull request closed without merging**
