### PR TITLE
Korean Translation

### PR DESCRIPTION
**Pull request by narusas**
## Description 

Korean Translation 

## Additional Information
Translated: Vuejs Korea  Slack (https://vuejs-korea.slack.com) Members

### CODE REVIEW

**Comment by NataliaTepluhina** [comment]
@narusas thank you so much for the translation work! 🙇🏻  I believe we don't need all the translated changes in diffs, could you please edit the PR to have only a link to the hosted translation website like here? https://github.com/vuejs/docs-next/pull/775/files#diff-9b73f4a12efe0be8829d902ad280c132505c19c2f41c0463375437e5112fab7bR402

**Comment by narusas** [comment]
Hi. 
Can I use .vuejs.org ?

**Comment by NataliaTepluhina** [comment]
@narusas I think it should be a preferred option. @bencodezen would you mind if I chime you in as you have an access to the domain?

**Comment by narusas** [comment]
Yes. Thank  you :)

**Comment by bencodezen** [comment]
Hi @narusas! Thanks for the PR. It looks like you're trying to merge into the master branch here, but this repo manages the English translation, so we have to decline this one.

Let's continue our conversation in https://github.com/vuejs/docs-next/pull/805

**Pull request closed without merging**
