### PR TITLE
add korean translation site link

### PR DESCRIPTION
**Pull request by narusas**
add translation links

### CODE REVIEW

**Review by bencodezen — CHANGES_REQUESTED** [review]
Hi @narusas! Where is the original repo for this?

Update: Disregard. I found it. It looks like it's a personal repo.

Have you been in touch with the Korean translation community from Vue 2?

https://github.com/vuejs-kr/

**Comment by ChangJoo-Park** [comment]
Hello @bencodezen , I am owner of [vuejs-kr](https://github.com/vuejs-kr) org. @narusas moves Vue.js 3 Korean docs into vuejs-kr.  Can you set a domain **https://v3.ko.vuejs.org/** for **https://v3-vuejs-korea.netlify.app/** ?

**Comment by skirtles-code** [comment]
Is this the new repo?

https://github.com/vuejs-kr/docs-next

If so, could someone enable *Issues* for that repository?

**Comment by narusas** [comment]
yes I have enable issues.

**Comment by skirtles-code** [comment]
Closes #756.

**Comment by bencodezen** [comment]
> Hello @bencodezen , I am owner of [vuejs-kr](https://github.com/vuejs-kr) org. @narusas moves Vue.js 3 Korean docs into vuejs-kr. Can you set a domain **https://v3.ko.vuejs.org/** for **https://v3-vuejs-korea.netlify.app/** ?

Hey @ChangJoo-Park! Thanks for the comment. I'll take a look to get those things moved over. Appreciate it!

**Comment by yyx990803** [comment]
I've added CNAME record for v3.ko.vuejs.org on the DNS.

**Comment by bencodezen** [comment]
@ChangJoo-Park Can you provide me permissions to the repo for the translation? I need to add it to the Netlify account on our side so we can hook everything up.

**Comment by narusas** [comment]
@bencodezen HI, I give you write permission to https://github.com/vuejs-kr/docs-next

**Comment by bencodezen** [comment]
> https://github.com/vuejs-kr/docs-next

Thanks @narusas! It looks ilke I need access to the organization vuejs-kr in order to add the site to the Netlify plan. Let me know when that's done!

**Comment by skirtles-code** [comment]
@ChangJoo-Park @narusas I'm not sure who can grant the relevant permissions to @bencodezen but we need that sorting before we can put this live. Thanks.

**Comment by narusas** [comment]
@bencodezen 
https://v3.ko.vuejs.org is ready. 

Please merge this PR  :)

**Comment by narusas** [comment]
@skirtle 
What permission is needed on  vuejs-kr/docs-next ?

**Review by bencodezen — APPROVED** [review]
Everything is good now! 

Apologies for the complications in getting this approved. There were just a lot of moving parts in this PR and unfortunately permissions were tricky to move around.

Congrats on the v3 translation!

**Pull request merged**
