### PR TITLE
Feat/support vue page

### PR DESCRIPTION
**Pull request by marina-mosti**
Adds and refactors the vue support page 
Closes issue #207 

Preview: https://deploy-preview-313--vue-docs-next-preview.netlify.app/support-vuejs/

### CODE REVIEW

**Comment by fatony788** [comment]
ghuh

**Comment by NataliaTepluhina** [comment]
@marina-mosti Netlify deployment throws an error `ReferenceError: window is not defined`

**Comment by marina-mosti** [comment]
> @marina-mosti Netlify deployment throws an error `ReferenceError: window is not defined`

Thanks @NataliaTepluhina I just noticed, the last commit should fix. Also added a couple missing logos

**Comment by NataliaTepluhina** [comment]
@marina-mosti thank you for taking a huge effort for moving this page! It looks great!

Would you mind also adding a sidebar there and keeping the container `max-width: 740px;` (I believe it's a default VuePress one). It looks a bit unpolished w/o sidebar:

Screenshot 2020-07-22 at 12 45 39

**Comment by marina-mosti** [comment]
Hey @NataliaTepluhina, ended up refactoring the whole thing into `markdown` with a couple components sprinkled in between. Looks neater, and should be easier to maintain.

**Comment by NataliaTepluhina** [comment]
@marina-mosti thank you for taking an effort an implementing all the changes 🙇🏻  Looks good to me!

**Pull request merged**
